repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
       - id: mypy
         additional_dependencies: [types-PyYAML==6.0.12.20250516]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest test
        language: system
        types: [python]
        env:
          PYTHONPATH: .
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=5000']
