import random

print(10)

ans = []

for i in range(10):
    ans_temp = []
    for j in range(100):
        if random.random() < 0.65:
            ans_temp.append("A")
        else:
            ans_temp.append("G")
    ans.append(ans_temp)

for i in range(50):
    i = random.randint(0, 9)
    j = random.randint(0, 99)
    ans[i][j] = "C" if i % 2 == 0 else "T"

print(*["".join(a) for a in ans], sep="\n")

"""

10
GGAAGAAAAAAAAAAGCAAGACAAAAGGGAAAGCAAGAAGAAAGGGAGGGAAGGAGGAAAAGAGAAAAGAACGAGGAGGAGAAGAGAGAGAAAGGAAGGA
AGGAAAAAAAGAGAAAAGGTAAAAAATGAAAAAAAGAAGAGAAGAAAGGAATGGAAAATAAAGAAAAGAAAGAGAGAGGGAAGAGAAGTGTAGAAAAAGA
GGAAAAAACAGAGAGGAAACAGGCGAAAGACAAAAGAGGAGAAAGAAAAAGGGAAGAGCGGAGAGGAAAACGCGGGAGAAAAGAGCAAAAGAGGGGGAGA
AAAAGGGAGGAGGAGAAGGAAAGAAGAAAAGATAAAGGAAAAGGAAGGAGAAAATAAAAGAAAAGGAGTGAAAAGAGGAAAATTAAAGGGAAGAAGAAGA
GAGGGGGGAAAAAGAAGAAACAAAGGACAGAAAAAAAAAAAACAAGAAACGCACAAGAAAGAAAAAGAGGAAAAGAGAACGAGAAACGGACGGAGAAGAA
GGAAGAGAAATGAAAGTGGGAGAAAGGAGGGGGAAGGAGAAAAGAATAGAAGAAGAAAAGAGAAGGAAAAGGAGAAAGAAAAAAAAGGAAAAGAAAGAGG
CAAAAAAAGAGGAAAAAAAAAAAAGAAGGGGAGAAAAAAGAAAAAAAGGGGGAAGGCAAGGAGGGGGAAGAAAAGAGAAAGGAAGAGAAGGGAGAAAAGG
AAAAAAAAAAGAAAGAGAAAAAAGAAAAGGAGGAGGAAAAAAGGGAAAGAAGAAAAAGGAGAAAGAGAAAAAAAAAGGAAAAAGAAGTAGAGAAGGAAAA
AGGAAAAAAAGAAAGCGAAAAGCGGAAAAAAAAAAAAAAGGAGAGAGAAAAAAGAGAAAAAGAAGGGGAAAAAGAAAAAAAAAAAGAAAGGAAAAAGGAG
GGAAGATAAGAATAGGAAGAGGGGAAGAATGTAGAAAGATGAAAAAAAAGAAAGAAATAATGAAAAATAGAGTAGAAAGAAGAAAAAGAGAAGAAAGAGA

"""
